"""Stage 4: Block Grid → Litematica / Schematic / Sponge Schematic file.

Supports:
- .litematic (Litematica mod) via litemapy
- .schematic (MCEdit / WorldEdit classic) via nbtlib
- .schem (Sponge / modern WorldEdit) via nbtlib
"""

from pathlib import Path

import nbtlib

from api.core.types import BlockGrid, PipelineConfig, SchematicOutput
from api.utils.logging import get_logger

log = get_logger(__name__)

SUPPORTED_FORMATS = ("litematic", "schematic", "schem")


def run(block_grid: BlockGrid, config: PipelineConfig) -> SchematicOutput:
    fmt = config.output_format
    if fmt == "litematic":
        return _export_litematic(block_grid, config)
    elif fmt == "schematic":
        return _export_schematic(block_grid, config)
    elif fmt == "schem":
        return _export_sponge(block_grid, config)
    else:
        raise ValueError(
            f"Unsupported format: {fmt}. Supported: {SUPPORTED_FORMATS}"
        )


def export_format(
    block_grid: BlockGrid,
    output_dir: Path,
    fmt: str,
    colorless: bool = False,
) -> Path:
    """Export a block grid to a specific format on disk. Returns the file path.

    If colorless=True, every block is replaced with minecraft:white_concrete.
    """
    grid = block_grid
    if colorless:
        grid = _make_colorless(block_grid)

    output_dir.mkdir(parents=True, exist_ok=True)

    if fmt == "litematic":
        return _write_litematic(grid, output_dir / "output.litematic")
    elif fmt == "schematic":
        return _write_schematic(grid, output_dir / "output.schematic")
    elif fmt == "schem":
        return _write_sponge(grid, output_dir / "output.schem")
    else:
        raise ValueError(f"Unsupported format: {fmt}. Supported: {SUPPORTED_FORMATS}")


def _make_colorless(block_grid: BlockGrid) -> BlockGrid:
    """Return a copy of the grid with all blocks set to white_concrete."""
    from api.core.types import BlockMapping
    blocks = [
        BlockMapping(
            block_id="minecraft:white_concrete",
            position=b.position,
            reason="colorless",
        )
        for b in block_grid.blocks
    ]
    return BlockGrid(
        blocks=blocks,
        dimensions=block_grid.dimensions,
        palette=["minecraft:white_concrete"],
    )


# ── Litematica (.litematic) ─────────────────────────────────────────────

def _write_litematic(block_grid: BlockGrid, output_path: Path) -> Path:
    try:
        from litemapy import Region, BlockState
    except ImportError:
        raise ImportError("Install litemapy: pip install litemapy")

    dx, dy, dz = block_grid.dimensions
    reg = Region(0, 0, 0, dx, dy, dz)

    unique_states: dict[str, BlockState] = {}
    placed = 0

    for block in block_grid.blocks:
        bid = block.block_id
        if bid not in unique_states:
            unique_states[bid] = BlockState(bid)
        x, y, z = block.position
        if 0 <= x < dx and 0 <= y < dy and 0 <= z < dz:
            reg.setblock(x, y, z, unique_states[bid])
            placed += 1

    schem = reg.as_schematic(
        name="craftfrom_output",
        author="craftfrom",
        description="Generated by CraftFrom",
    )
    schem.save(str(output_path))
    log.info(f"Exported {placed} blocks (litematic) to {output_path}")
    return output_path


def _export_litematic(block_grid: BlockGrid, config: PipelineConfig) -> SchematicOutput:
    config.output_dir.mkdir(parents=True, exist_ok=True)
    path = _write_litematic(block_grid, config.output_dir / "output.litematic")
    return SchematicOutput(
        path=path,
        format="litematic",
        block_count=len(block_grid.blocks),
        dimensions=block_grid.dimensions,
    )


# ── Classic .schematic (MCEdit / WorldEdit) ──────────────────────────────

_BLOCK_NAME_TO_LEGACY: dict[str, tuple[int, int]] = {
    "minecraft:air": (0, 0),
    "minecraft:stone": (1, 0),
    "minecraft:granite": (1, 1),
    "minecraft:diorite": (1, 3),
    "minecraft:andesite": (1, 5),
    "minecraft:grass_block": (2, 0),
    "minecraft:dirt": (3, 0),
    "minecraft:cobblestone": (4, 0),
    "minecraft:oak_planks": (5, 0),
    "minecraft:spruce_planks": (5, 1),
    "minecraft:birch_planks": (5, 2),
    "minecraft:jungle_planks": (5, 3),
    "minecraft:acacia_planks": (5, 4),
    "minecraft:dark_oak_planks": (5, 5),
    "minecraft:sand": (12, 0),
    "minecraft:red_sandstone": (179, 0),
    "minecraft:sandstone": (24, 0),
    "minecraft:smooth_sandstone": (24, 2),
    "minecraft:cut_sandstone": (24, 1),
    "minecraft:glass": (20, 0),
    "minecraft:white_wool": (35, 0),
    "minecraft:orange_wool": (35, 1),
    "minecraft:magenta_wool": (35, 2),
    "minecraft:light_blue_wool": (35, 3),
    "minecraft:yellow_wool": (35, 4),
    "minecraft:lime_wool": (35, 5),
    "minecraft:pink_wool": (35, 6),
    "minecraft:gray_wool": (35, 7),
    "minecraft:light_gray_wool": (35, 8),
    "minecraft:cyan_wool": (35, 9),
    "minecraft:purple_wool": (35, 10),
    "minecraft:blue_wool": (35, 11),
    "minecraft:brown_wool": (35, 12),
    "minecraft:green_wool": (35, 13),
    "minecraft:red_wool": (35, 14),
    "minecraft:black_wool": (35, 15),
    "minecraft:bricks": (45, 0),
    "minecraft:obsidian": (49, 0),
    "minecraft:oak_log": (17, 0),
    "minecraft:spruce_log": (17, 1),
    "minecraft:bookshelf": (47, 0),
    "minecraft:snow_block": (80, 0),
    "minecraft:clay": (82, 0),
    "minecraft:glowstone": (89, 0),
    "minecraft:stone_bricks": (98, 0),
    "minecraft:iron_block": (42, 0),
    "minecraft:gold_block": (41, 0),
    "minecraft:quartz_block": (155, 0),
    "minecraft:white_terracotta": (159, 0),
    "minecraft:orange_terracotta": (159, 1),
    "minecraft:magenta_terracotta": (159, 2),
    "minecraft:light_blue_terracotta": (159, 3),
    "minecraft:yellow_terracotta": (159, 4),
    "minecraft:lime_terracotta": (159, 5),
    "minecraft:pink_terracotta": (159, 6),
    "minecraft:gray_terracotta": (159, 7),
    "minecraft:light_gray_terracotta": (159, 8),
    "minecraft:cyan_terracotta": (159, 9),
    "minecraft:purple_terracotta": (159, 10),
    "minecraft:blue_terracotta": (159, 11),
    "minecraft:brown_terracotta": (159, 12),
    "minecraft:green_terracotta": (159, 13),
    "minecraft:red_terracotta": (159, 14),
    "minecraft:black_terracotta": (159, 15),
    "minecraft:terracotta": (172, 0),
    "minecraft:prismarine": (168, 0),
    "minecraft:sea_lantern": (169, 0),
    "minecraft:white_concrete": (251, 0),
    "minecraft:orange_concrete": (251, 1),
    "minecraft:magenta_concrete": (251, 2),
    "minecraft:light_blue_concrete": (251, 3),
    "minecraft:yellow_concrete": (251, 4),
    "minecraft:lime_concrete": (251, 5),
    "minecraft:pink_concrete": (251, 6),
    "minecraft:gray_concrete": (251, 7),
    "minecraft:light_gray_concrete": (251, 8),
    "minecraft:cyan_concrete": (251, 9),
    "minecraft:purple_concrete": (251, 10),
    "minecraft:blue_concrete": (251, 11),
    "minecraft:brown_concrete": (251, 12),
    "minecraft:green_concrete": (251, 13),
    "minecraft:red_concrete": (251, 14),
    "minecraft:black_concrete": (251, 15),
    "minecraft:white_stained_glass": (95, 0),
    "minecraft:blue_stained_glass": (95, 11),
}


def _legacy_id(block_id: str) -> tuple[int, int]:
    """Map a modern block ID to legacy (numeric ID, data value).
    Falls back to stone (1, 0) for unmapped blocks.
    """
    return _BLOCK_NAME_TO_LEGACY.get(block_id, (1, 0))


def _write_schematic(block_grid: BlockGrid, output_path: Path) -> Path:
    dx, dy, dz = block_grid.dimensions

    blocks_array = bytearray(dx * dy * dz)
    data_array = bytearray(dx * dy * dz)

    placed = 0
    for block in block_grid.blocks:
        x, y, z = block.position
        if 0 <= x < dx and 0 <= y < dy and 0 <= z < dz:
            idx = (y * dz + z) * dx + x
            bid, dval = _legacy_id(block.block_id)
            blocks_array[idx] = bid & 0xFF
            data_array[idx] = dval & 0xF
            placed += 1

    nbt = nbtlib.Compound({
        "Schematic": nbtlib.Compound({
            "Width": nbtlib.Short(dx),
            "Height": nbtlib.Short(dy),
            "Length": nbtlib.Short(dz),
            "Materials": nbtlib.String("Alpha"),
            "Blocks": nbtlib.ByteArray(blocks_array),
            "Data": nbtlib.ByteArray(data_array),
            "Entities": nbtlib.List[nbtlib.Compound](),
            "TileEntities": nbtlib.List[nbtlib.Compound](),
        })
    })

    nbt_file = nbtlib.File(nbt["Schematic"], gzipped=True)
    nbt_file.save(str(output_path))
    log.info(f"Exported {placed} blocks (schematic) to {output_path}")
    return output_path


def _export_schematic(block_grid: BlockGrid, config: PipelineConfig) -> SchematicOutput:
    config.output_dir.mkdir(parents=True, exist_ok=True)
    path = _write_schematic(block_grid, config.output_dir / "output.schematic")
    return SchematicOutput(
        path=path,
        format="schematic",
        block_count=len(block_grid.blocks),
        dimensions=block_grid.dimensions,
    )


# ── Sponge Schematic v2 (.schem) ────────────────────────────────────────

def _write_sponge(block_grid: BlockGrid, output_path: Path) -> Path:
    dx, dy, dz = block_grid.dimensions

    palette_map: dict[str, int] = {"minecraft:air": 0}
    palette_idx = 1
    block_data_list: list[int] = []

    block_by_pos: dict[tuple[int, int, int], str] = {}
    for block in block_grid.blocks:
        x, y, z = block.position
        if 0 <= x < dx and 0 <= y < dy and 0 <= z < dz:
            block_by_pos[(x, y, z)] = block.block_id

    placed = 0
    for y in range(dy):
        for z in range(dz):
            for x in range(dx):
                bid = block_by_pos.get((x, y, z), "minecraft:air")
                if bid not in palette_map:
                    palette_map[bid] = palette_idx
                    palette_idx += 1
                varint = palette_map[bid]
                while varint > 0x7F:
                    block_data_list.append((varint & 0x7F) | 0x80)
                    varint >>= 7
                block_data_list.append(varint & 0x7F)
                if bid != "minecraft:air":
                    placed += 1

    palette_nbt = nbtlib.Compound({
        nbtlib.String(k): nbtlib.Int(v) for k, v in palette_map.items()
    })

    schem = nbtlib.Compound({
        "Schematic": nbtlib.Compound({
            "Version": nbtlib.Int(2),
            "DataVersion": nbtlib.Int(3463),
            "Width": nbtlib.Short(dx),
            "Height": nbtlib.Short(dy),
            "Length": nbtlib.Short(dz),
            "Palette": palette_nbt,
            "PaletteMax": nbtlib.Int(palette_idx),
            "BlockData": nbtlib.ByteArray(block_data_list),
            "Metadata": nbtlib.Compound({
                "WEOffsetX": nbtlib.Int(0),
                "WEOffsetY": nbtlib.Int(0),
                "WEOffsetZ": nbtlib.Int(0),
            }),
        })
    })

    nbt_file = nbtlib.File(schem["Schematic"], gzipped=True)
    nbt_file.save(str(output_path))
    log.info(f"Exported {placed} blocks (sponge schem) to {output_path}")
    return output_path


def _export_sponge(block_grid: BlockGrid, config: PipelineConfig) -> SchematicOutput:
    config.output_dir.mkdir(parents=True, exist_ok=True)
    path = _write_sponge(block_grid, config.output_dir / "output.schem")
    return SchematicOutput(
        path=path,
        format="schem",
        block_count=len(block_grid.blocks),
        dimensions=block_grid.dimensions,
    )
