"""Stage 4: Block Grid → Litematica / Schematic file.

Uses litemapy to write .litematic files that can be loaded in-game
with the Litematica mod.
"""

from pathlib import Path

from api.core.types import BlockGrid, PipelineConfig, SchematicOutput
from api.utils.logging import get_logger

log = get_logger(__name__)


def run(block_grid: BlockGrid, config: PipelineConfig) -> SchematicOutput:
    if config.output_format == "litematic":
        return _export_litematic(block_grid, config)
    else:
        raise ValueError(f"Unsupported format: {config.output_format}. Currently only 'litematic' is supported.")


def _export_litematic(block_grid: BlockGrid, config: PipelineConfig) -> SchematicOutput:
    try:
        from litemapy import Schematic, Region, BlockState
    except ImportError:
        raise ImportError("Install litemapy: pip install litemapy")

    dx, dy, dz = block_grid.dimensions
    reg = Region(0, 0, 0, dx, dy, dz)

    unique_states: dict[str, BlockState] = {}
    placed = 0

    for block in block_grid.blocks:
        bid = block.block_id
        if bid not in unique_states:
            unique_states[bid] = BlockState(bid)
        x, y, z = block.position
        if 0 <= x < dx and 0 <= y < dy and 0 <= z < dz:
            reg.setblock(x, y, z, unique_states[bid])
            placed += 1

    schem = reg.as_schematic(
        name="craftfrom_output",
        author="craftfrom",
        description="Generated by CraftFrom",
    )

    config.output_dir.mkdir(parents=True, exist_ok=True)
    output_path = config.output_dir / "output.litematic"
    schem.save(str(output_path))

    log.info(f"Exported {placed} blocks to {output_path}")
    return SchematicOutput(
        path=output_path,
        format="litematic",
        block_count=placed,
        dimensions=(dx, dy, dz),
    )
